spring:
  datasource:
    username: hyerim
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/netflixdb?serverTimezone=Asia/Seoul
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
